### ISSUE TITLE
Import data visualization tools from tools

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/data-visualization#1]
Import data visualization tools from https://github.com/roboticslab-uc3m/tools :
- [x] meanVar
- [x] plotTrajectories
- [x] plotTrajectories3D
- [x] boxPlot

**Comment by jgvictores** [comment]
@RaulFdzbis Coult you delete them from https://github.com/roboticslab-uc3m/tools ?

**Comment by jgvictores** [comment]
PS: Updated list, missing `meanVar`

**Comment by RaulFdzbis** [comment]
> @RaulFdzbis Could you delete them from https://github.com/roboticslab-uc3m/tools ?

Ups forgot to push it :_)

With respect to `meanVar`, that program is not for visualization, it just outputs a .txt file with the mean and variance from a dataset, no visualization involved, I don't know if it should go here.

**Comment by jgvictores** [comment]
Yes, please move it. I'd like to move all related with data treatment to this repo (we might change its name in the future). Thanks!
